production:
  decay_remembers:
    class: DecayRemembersJob
    queue: default
    schedule: at midnight every day
  send_due_reports:
    class: SendDueReportsJob
    queue: default
    schedule: every 15 minutes
  send_daily_backups:
    class: SendDailyBackupsJob
    queue: default
    schedule: at 3am every day
